---
- name: Enable user_allow_other in fuse.conf
  lineinfile:
    path: /etc/fuse.conf
    regexp: '^#user_allow_other'
    line: 'user_allow_other'
    backup: yes

- name: Format and mount data drive
  block:
    - name: Format drive with ext4
      filesystem:
        fstype: ext4
        dev: /dev/sdb

    - name: Create data cache directory
      file:
        path: "{{ ll_cache_location }}"
        state: directory
        mode: '0755'
        owner: ubuntu
        group: ubuntu

    - name: Mount data drive
      mount:
        path: "{{ ll_cache_location }}"
        src: /dev/sdb
        fstype: ext4
        state: mounted
        opts: defaults,nofail
        dump: 0
        passno: 0

    - name: Set ownership of mounted directory
      file:
        path: "{{ ll_cache_location }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
        recurse: yes

    - name: Create config directory
      file:
        path: "{{ ll_cache_location }}/instance_501"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

- name: Create LucidLink mount point directory
  file:
    path: "{{ ll_mount_point }}"
    state: directory
    mode: '0755'
    owner: ubuntu
    group: ubuntu

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: yes
    
- name: Download latest LucidLink installer
  get_url:
    url: "https://www.lucidlink.com/download/latest/lin64/stable/"
    dest: /tmp/lucidlink.deb
    mode: '0644'

- name: Install LucidLink package
  apt:
    deb: /tmp/lucidlink.deb
    state: present

- name: Create password file for LucidLink
  copy:
    content: "PASSWORD='{{ ll_password }}'"
    dest: "/root/.{{ ll_filespace | replace('.', '-') }}.pwd"
    owner: root
    group: root
    mode: '0400'
  no_log: true

- name: Create LucidLink service file
  template:
    src: lucidlink.service.j2
    dest: "/etc/systemd/system/{{ ll_filespace | replace('.', '-') }}.service"
    owner: root
    group: root
    mode: '0644'
  notify: reload systemd

- name: Force handlers to run now
  meta: flush_handlers

- name: Enable and start LucidLink service
  systemd:
    name: "{{ ll_filespace | replace('.', '-') }}"
    state: started
    enabled: yes

- name: Wait for LucidLink service to be linked
  shell: |
    until /usr/bin/lucid2 --instance 501 status | grep -q 'Linked' ; do sleep 5; done
  args:
    executable: /bin/bash
  changed_when: false

- name: Set data cache location for LucidLink
  command: /usr/bin/lucid2 --instance 501 config --set --DataCache.Location {{ ll_cache_location }}

- name: Restart LucidLink service
  systemd:
    name: "{{ ll_filespace | replace('.', '-') }}"
    state: restarted

- name: Set data cache size for LucidLink
  command: /usr/bin/lucid2 --instance 501 config --set --DataCache.Size {{ ll_data_cache_size }}
