---
- name: Configure LucidLink (Ubuntu)
  block:
    - name: Configure cache size
      command: >
        su - lucidlink -c "/usr/bin/lucid2
        --instance {{ '501' if ll_version == '2' else '2001' }}
        config --set --DataCache.Size {{ ll_data_cache_size }}"
      register: cache_size_result
      ignore_errors: yes
      
    - name: Configure cache location
      command: >
        su - lucidlink -c "/usr/bin/lucid2
        --instance {{ '501' if ll_version == '2' else '2001' }}
        config --set --DataCache.location {{ ll_cache_location }}"
      register: cache_location_result
      ignore_errors: yes
  when: ansible_distribution == "Ubuntu"

- name: Configure LucidLink (RHEL)
  block:
    - name: Configure cache size
      command: >
        su - lucidlink -c "/bin/lucid2 --instance 501
        config --set --DataCache.Size {{ ll_data_cache_size }}"
      register: cache_size_result
      ignore_errors: yes
      
    - name: Configure cache location
      command: >
        su - lucidlink -c "/bin/lucid2 --instance 501
        config --set --DataCache.location {{ ll_cache_location }}"
      register: cache_location_result
      ignore_errors: yes
  when: ansible_distribution != "Ubuntu"

- name: Configure cache and logging
  block:
    - name: Create logging directory
      file:
        path: /etc/lucidlink
        state: directory
        mode: '0755'
        owner: lucidlink
        group: lucidlink

    - name: Configure logging
      copy:
        src: monitoring.conf
        dest: /etc/lucidlink/logging.conf
        mode: '0644'
        owner: lucidlink
        group: lucidlink
      notify: restart_lucidlink

  rescue:
    - name: Fail the play
      fail:
        msg: "Configuration failed. Please check the logs for more information."
      when: (cache_size_result is defined and cache_size_result is failed) or 
            (cache_location_result is defined and cache_location_result is failed)
