---
- name: Check system requirements
  block:
    - name: Get system memory
      ansible.builtin.shell: free -b | awk 'NR==2 {print $2}'
      register: total_memory
      changed_when: false
      
    - name: Get available disk space
      ansible.builtin.shell: df -B1 {{ ll_cache_location | dirname }} | awk 'NR==2 {print $4}'
      register: available_space
      changed_when: false
      
    - name: Verify system meets requirements
      assert:
        that:
          - total_memory.stdout|int >= 4294967296  # 4GB minimum
          - available_space.stdout|int >= 10737418240  # 10GB minimum
        fail_msg: "System does not meet minimum requirements: 4GB RAM and 10GB free space"
        success_msg: "System meets minimum requirements"

- name: Set OS-specific variables
  set_fact:
    os_type: >-
      {% if ansible_distribution == 'Ubuntu' %}ubuntu
      {% elif ansible_distribution == 'Amazon' %}amazon_linux_2023
      {% else %}unknown{% endif %}

- name: Set package lists
  set_fact:
    os_packages:
      ubuntu:
        - fuse
        - curl
        - python3
        - python3-pip
        - python3-dev
        - build-essential
      amazon_linux_2023:
        - fuse
        - curl
        - python3
        - python3-pip
        - python3-devel
        - gcc
      
- name: Install required packages
  package:
    name: "{{ os_packages[os_type] }}"
    state: present
  register: package_install
  retries: 3
  delay: 5
  until: package_install is success
  
- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ ll_mount_point }}"
    - "{{ ll_cache_location }}"
  register: dir_creation
  
- name: Set up logging directory
  file:
    path: /var/log/lucidlink-ansible-deploy
    state: directory
    mode: '0755'
    
- name: Configure system limits
  pam_limits:
    domain: '*'
    limit_type: "{{ item.type }}"
    limit_item: "{{ item.item }}"
    value: "{{ item.value }}"
  loop:
    - { type: 'soft', item: 'nofile', value: '65535' }
    - { type: 'hard', item: 'nofile', value: '65535' }
  notify: reload_limits
